version: '3.5'

services:
  zabbix-proxy:
    image: zabbix/zabbix-proxy-sqlite3:alpine-7.0-latest
    container_name: corewise-zabbix-proxy
    environment:
      ZBX_HOSTNAME: corewise-proxy
      ZBX_SERVER_HOST: ${ZABBIX_SERVER_IP:-192.168.1.100}
      ZBX_SERVER_PORT: 10051
    volumes:
      - ./scripts:/usr/lib/zabbix/externalscripts:ro
    ports:
      - "10051:10051"
    restart: always
    labels:
      - "coolify.managed=true"

  zabbix-sender:
    build:
      context: .
      dockerfile: Dockerfile.zabbix.sender
    image: corewise-zabbix-sender:latest
    container_name: corewise-zabbix-sender
    environment:
      ZBX_SERVER_HOST: zabbix-proxy
      ZBX_SERVER_PORT: 10051
    restart: always
    labels:
      - "coolify.managed=true" 